name: Block_Xray
version: '${project.version}'
main: com.github.falledcan.block_xray.Block_Xray
api-version: '1.19'
authors: [ falled_can ]
description: This is for monitoring and please do not abuse it
commands:
  xray:
    description: 周囲の鉱石を発光させて表示します (管理者用)
    usage: /xray [鉱石|all|off|reload]
    permission: blockxray.use
permissions:
  blockxray.use:
    description: /xray を使用できる
    default: op
  blockxray.reload:
    description: /xray reload を使用できる
    default: op
